global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'secan-monitor'

scrape_configs:
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
        labels:
          cluster: 'secan-cluster'
          environment: 'development'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
